title: Jakub Krawczyk
email: "22723539+jakubkrawczyk@users.noreply.github.com"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: "jakubkrawczyk/jekyll-profile-page@main"

cover_photo:
  url: assets/images/cover.jpg
  alt: "Mountains covered with snow and dark sky in the background"

profile_picture: assets/images/photo.png

author:
  name: "Jakub Krawczyk"
  occupation: "Software Engineer"
  location:
    name: "Poland"

# action_button:
#   label: "Call to action button"
#   icon: "fas fa-briefcase"

work:
  -
    name: "Wunderman Thompson Technology"
    url: "https://www.wundermanthompson.com/service/technology"

projects:
  -
    name: "This Jekyll theme"
    url: "https://github.com/jakubkrawczyk/jekyll-profile-page"

social:
  -
    url: "https://github.com/jakubkrawczyk"
    title: "GitHub Profile Page"
    icon: "fab fa-github"
  - 
    url: "https://www.linkedin.com/in/jakub-krawczyk-61a1b1173"
    title: "LinkedIn Profile Page"
    icon: "fab fa-linkedin"
